package net.sf.jclec.binarray;

import net.sf.jclec.ISpecies;


/**
 * MultipBinArrayIndividual (and subclasses) specific recombinator.  
 * 
 * @author Sebastian Ventura
 * @author Jose M. Moyano
 */

public abstract class MultipBinArrayRecombinator extends BinArrayRecombinator
{
	
	/////////////////////////////////////////////////////////////////
	// ------------------------------------------ Operation variables
	/////////////////////////////////////////////////////////////////

	/**
	 * Generated by Eclipse
	 */
	private static final long serialVersionUID = -2482775303204486624L;
	
	/** Individual species (taked from execution context) */
	protected transient MultipBinArraySpecies species;

	/////////////////////////////////////////////////////////////////
	// ------------------------------------------------- Constructors
	/////////////////////////////////////////////////////////////////

	/**
	 * Empty (default) constructor.
	 */
	public MultipBinArrayRecombinator() 
	{
		super();
	}

	/**
	 * {@inheritDoc}
	 */
	
	@Override
	protected void prepareRecombination() 
	{
		ISpecies species = context.getSpecies();
		if (species instanceof MultipBinArraySpecies) {
			// Set individuals speciess
			this.species = (MultipBinArraySpecies) species;
		}
		else {
			throw new IllegalStateException("Invalid population species");
		}		
	}
	
}
