package net.sf.jclec.binarray;

import net.sf.jclec.ISpecies;

/**
 * MultipBinArrayIndividual (and subclasses) specific mutator.  
 * 
 * @author Sebastian Ventura
 * @author Jose M. Moyano
 */

public abstract class MultipBinArrayMutator extends BinArrayMutator  
{
	/**
	 * Generated by Eclipse
	 */
	private static final long serialVersionUID = 2071164648724732318L;
	
	/** Individual species (taked from execution context) */
	protected transient MultipBinArraySpecies species;
	
	/**
	 * Empty (default) constructor.
	 */
	public MultipBinArrayMutator() 
	{
		super();
	}

	/////////////////////////////////////////////////////////////////
	// ----------------------------------------------- Public methods
	/////////////////////////////////////////////////////////////////
	
	// AbstractMutator methods
	
	/**
	 * {@inheritDoc}
	 */
	@Override
	protected void prepareMutation() 
	{
		ISpecies species = context.getSpecies();
		if (species instanceof MultipBinArraySpecies) {
			// Set individuals species
			this.species = (MultipBinArraySpecies) species;
			// Sets genotype schema
			this.schema = this.species.getGenotypeSchema();
		}
		else {
			throw new IllegalStateException("Invalid species in context");
		}
	}
}
